### ISSUE TITLE
Signing in and out multiple times per day overwrites hours on "Date Log" spreadsheet

### ISSUE THREAD

**Issue by Aerotusk** [Daltz333/GrizzlyTime-JavaFX#10]
Some of our members have left during a meeting and then come back, and their first section of hours gets overwritten by their second set in the "Date Log" spreadsheet. It seems like their total hours in the "Current" spreadsheet stays fine, though

**Comment by Daltz333** [comment]
This was the intended behavior, I don't really have any good ideas of managing multiple sign ins/out per day. Would greatly enjoy some help in this matter.

**Comment by Aerotusk** [comment]
Could you check to see if the cell in "Date Log" is already full, and if so, add the hours to it?

**Comment by Daltz333** [comment]
I like that implementation a lot. I shall indeed do that!

**Comment by Daltz333** [comment]
Added in 73a76a7
See releases for a testing version.
