### ISSUE TITLE
People who don't sign out before midnight can't sign in our out the next day

### ISSUE THREAD

**Issue by Aerotusk** [Daltz333/GrizzlyTime-JavaFX#11]
When students don't sign out by the end of the day, they get stuck in a perpetual cycle of "signing out," but they can never actually sign out. 

It would be nice if people were automatically signed out at the end of each day, but not awarded hours. Currently we have to erase some of the columns manually in order to allow them to sign back in.

**Comment by Daltz333** [comment]
I'll work on implementing that as soon as possible. I apologize for the delay in response! 
What I'll probably do is implement a separate column that tracks "last date logged in" and compare that way instead of the current implementation.

**Comment by Daltz333** [comment]
Can you verify that you are on version 1.1.2?
https://github.com/Daltz333/GrizzlyTime-JavaFX/releases

**Comment by Aerotusk** [comment]
Just updated from 1.1.1

**Comment by Daltz333** [comment]
@Aerotusk can you confirm fixed?

**Comment by Daltz333** [comment]
I'm gonna close this and assumed fix as my testing has shown this to be fixed.
