### ISSUE TITLE
Config.json saying that URL Is invalid after running program for 20 minutes

### ISSUE THREAD

**Issue by nmatthes4130** [Daltz333/GrizzlyTime-JavaFX#13]
Hello, when running program ran great for the first 20 minutes, everything was reporting to the google sheet, then all of a sudden I got an error saying the URL was wrong even though it is not. Can you help me out?

**Comment by Daltz333** [comment]
I'm pretty sure this is linked to the internet connectivity bug. If you lose internet for some reason and try to connect, it'll throw a URL error. Make sure you have a stable internet connection. This will be fixed sometime tomorrow. I'll keep this open until I confirm a fix. 

Workaround: Restart application with internet.

**Comment by nmatthes4130** [comment]
Even when I Ethernet in to make sure I’m good, it’s still throwing that error. Not sure. Thank you though.

-Nick Matthes
FRC Team 4130, Co-Advisor
2018 Detroit World Championship Finalist

________________________________

**Comment by Daltz333** [comment]
Hmm... Could you try the 1.1.3 Pre-Release in https://github.com/Daltz333/GrizzlyTime-JavaFX/releases/tag/v1.1.3-pre

**Comment by Daltz333** [comment]
It has some additional catching for internet related bugs.
Hm. Perhaps the protocol is being blocked. 🤔 
Or... the network adapter is falling asleep.

**Comment by nmatthes4130** [comment]
Yup will do. Thanks.

-Nick Matthes
FRC Team 4130, Co-Advisor
2018 Detroit World Championship Finalist

________________________________

**Comment by Daltz333** [comment]
@nmatthes4130 Just wanted to give you a heads up that v.1.2.0 is released and fixes quite a few things including a major bug where time would be reset >24 hours.

**Comment by nmatthes4130** [comment]
Getting an error that says check internet and database, I Created a new one and connected to ethernet and Wifi. Still having an issue.


-Nick Matthes

FRC Team 4130, Co-Advisor

2018 Detroit World Championship Finalist

________________________________

**Comment by Daltz333** [comment]
Could you send me the log file that's generated?
v1.2.1 generates log files to make debugging a lot easier. I'm so sorry about the inconvenience. This is puzzling me just as much as you.

**Comment by Daltz333** [comment]
I cannot seem to reproduce @nmatthes4130. The latest update outputs a log file so if you could update and send that whenever the error happens. I'd appreciate it a lot!

**Comment by Daltz333** [comment]
Aha! I think I found it! Did you by chance import the template file into your google sheet database? If you did, did you rename any of the sheet names?

**Comment by nmatthes4130** [comment]
Yes. Imported template and renamed the sheet.

-Nick Matthes
FRC Team 4130, Co-Advisor
2018 Detroit World Championship Finalist

________________________________

**Comment by Daltz333** [comment]
The "Current" and "Date Log" sheet **must** not be renamed. That would be what's throwing the exception. Just added a commit that works around it by creating the Current and Date Log sheet. 

For specifics on vocabulary, 
Spreadsheet is the overall google sheet
Sheet is the sub sheets in the spreadsheet (in our case it'd be Current and Date Log)

**Comment by Daltz333** [comment]
Any objections to me marking this as closed?

**Comment by Daltz333** [comment]
Feel free to re-open if you still have this issue.
