### ISSUE TITLE
After computer suspend, System will not resume camera.

### ISSUE THREAD

**Issue by 770352** [Daltz333/GrizzlyTime-JavaFX#14]
Win8.1, 1.1.0? If the PC suspends during program operation with a camera, The camera will be frozen sometimes.

**Comment by Daltz333** [comment]
Restarting the application is a temp fix for now.

A more permanent fix that I'll implement is for it to "check" if the camera stream is still open, and if it isn't to reopen it.

**Comment by Daltz333** [comment]
Fixed
